{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "305af127_d096887f",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 5
      },
      "lineNbr": 0,
      "author": {
        "id": 21651
      },
      "writtenOn": "2022-06-01T09:28:41Z",
      "side": 1,
      "message": "Doesn\u0027t connect after first reboot.",
      "revId": "a2d1f399ca65b154d77acec32b3f117407085c21",
      "serverId": "1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71"
    }
  ]
}